// generated by "sampctl package generate"
#include "CustomSkins.inc";
#include "evi.inc";
#include "timestamptodate.inc";

main() {
	// write tests for libraries here and run "sampctl package run"
}